// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmlRciH3eOI-WtB_YXJgN_SBAVEIYhd3M',
    appId: '1:882159044456:web:42f5635cf55a58bf8f38dd',
    messagingSenderId: '882159044456',
    projectId: 'expertmoney-3f96c',
    authDomain: 'expertmoney-3f96c.firebaseapp.com',
    storageBucket: 'expertmoney-3f96c.firebasestorage.app',
    measurementId: 'G-MMZ7NWBW74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCU3juBuh258dLXQBHYYcf--0enZZOOXU',
    appId: '1:882159044456:android:132b0098bf8832a88f38dd',
    messagingSenderId: '882159044456',
    projectId: 'expertmoney-3f96c',
    storageBucket: 'expertmoney-3f96c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdHFAD_EnT_zBTxnvXtzKAnawFyn1m-8g',
    appId: '1:882159044456:ios:0ec866a8434baf7e8f38dd',
    messagingSenderId: '882159044456',
    projectId: 'expertmoney-3f96c',
    storageBucket: 'expertmoney-3f96c.firebasestorage.app',
    iosBundleId: 'com.expertmoney.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdHFAD_EnT_zBTxnvXtzKAnawFyn1m-8g',
    appId: '1:882159044456:ios:0ec866a8434baf7e8f38dd',
    messagingSenderId: '882159044456',
    projectId: 'expertmoney-3f96c',
    storageBucket: 'expertmoney-3f96c.firebasestorage.app',
    iosBundleId: 'com.expertmoney.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmlRciH3eOI-WtB_YXJgN_SBAVEIYhd3M',
    appId: '1:882159044456:web:db1367bb71ca25768f38dd',
    messagingSenderId: '882159044456',
    projectId: 'expertmoney-3f96c',
    authDomain: 'expertmoney-3f96c.firebaseapp.com',
    storageBucket: 'expertmoney-3f96c.firebasestorage.app',
    measurementId: 'G-GGTW1R48NF',
  );
}
